config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    member do
      put "like", to:    "posts#upvote"
      put "dislike", to: "posts#downvote"
      post :repost
    end
    resources :comments do
      member do
        put "like", to:    "comments#upvote"
        put "dislike", to: "comments#downvote"
      end
      resources :notations
    end
  end
  resources :users do
    member do
      get :following, :followers
    end
  end
  get 'feed', to: 'static_pages#home'
  get 'static_pages/help'
  get 'y/:tag', to: 'tags#show', as: :tag
  get 'yarnns', to: 'tags#index'
  match '/about', to: 'static_pages#about', via: 'get'
  put 'ipsum', to: "words#generate_ipsum"
  get 'ipsum', to: "words#generate_ipsum"
  
  resources :relationships, only: [:create, :destroy]

  resources :notifications do
    member do
      get :toggle_read
    end
  end
  
  resources :sharings,      only: [:create, :destroy]
  
  authenticated do
    root :to => 'static_pages#home', as: :authenticated
  end

  root :to => 'home#index'
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if user_signed_in?
      @post = current_user.posts.build
      @feed_items = current_user.feed.order("created_at DESC")
      respond_to do |format| 
        format.html
        format.js
      end
    end
  end

  def help
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/help.html.erb
<div id="main-content">
  <div id="content" class="col-md-6 col-md-offset-3">
    <div class="btn-group pull-right">
      <%= link_to ipsum_path, method: :put, class: "btn btn-default btn-xs" do %>
        <span class="glyphicon glyphicon-random">Generate Ipsum</span>
      <% end %>
  	</div>
	</div>
</div>

app/views/static_pages/home.html.erb
<div class="user-left-column">
  <%= render 'posts/left' %>
</div>

<div class="user-mid-column">
  <div id="content" class="col-md-12">
    <% @feed_items.each do |item| %>
      <div class="main-content">
      <div class="link row clearfix">
        <div class="post-box">
    		<div class="row">
    	    <div class="col-md-2">
    	    	<%= link_to user_path(item.user) do
    		     	image_tag(item.user.avatar.url, width: 55, class: "img-circle pull-left")
    		  	end %>
    			</div>
    			
    			<div class="col-md-10-offset-2">
    			  <% if item.user == current_user %>
              <div class="btn-group pull-right">
              <% unless item.post_id? %>
              	<%= link_to edit_post_path(item), class: "btn btn-xs", style: "color: #039087;" do %>
              		<span class="glyphicon glyphicon-cog"></span>
              	<% end %>
              <% end %>
            	<%= link_to item, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-xs", style: "color: #039087;" do %>
            		<span class="glyphicon glyphicon-trash"></span>
            	<% end %>
            	</div>
            <% end %>
    		  	<h5 style="margin-top: 0px">
    		  	<% if item.post_id? %>
    		  	 <small class="author"><span class="glyphicon glyphicon-retweet"></span> Reposted by <%= link_to item.user.username, user_path(item.user) %> <span class="glyphicon glyphicon-star"></span> <%= item.user.reputation %>
    		  	<% else %>
    		  	<small class="author"><%= link_to item.user.username, user_path(item.user) %> <span class="glyphicon glyphicon-star"></span> <%= item.user.reputation %>
            <% end %> 
             - <%= time_ago_in_words(item.created_at) %> ago 
      		  	
            <% if item.post_id? %>
              <br />Originally <%= link_to "posted", post_path(item.post) %> by <%= link_to item.post.user.username, user_path(item.post.user) %> 
              <span class="glyphicon glyphicon-star"></span> <%= item.post.user.reputation %>
              - <%= time_ago_in_words(item.post.created_at) %> ago
            <% end %>
            </small></h5>
            
            <div class="post-text">
              <% if item.post_id? %>
        			  <%= if item.post.image? 
                  image_tag item.post.image, class: "image"
                end %>
                <%= if item.post.video? 
                  video_tag item.post.video, class: "image", :controls => true
                end %>
                <%= if item.post.audio? 
                  audio_tag item.post.audio, class: "audio", :controls => true
                end %>
                <br />
                <%= item.post.content %>
              <% else %>
        			  <%= if item.image? 
                  image_tag item.image, class: "image"
                end %>
                <%= if item.video? 
                  video_tag item.video, class: "image", :controls => true
                end %>
                <%= if item.audio? 
                  audio_tag item.audio, class: "audio", :controls => true
                end %>
                <br />
                <%= item.content %>
              <% end %>
              <br />
              
              <div class="tags">
              <span class="glyphicon glyphicon-tags"></span>&nbsp; 
                <% item.tag_list.map.each do |tag| %>
                  <div class="tags">
                    <i><%= link_to tag, tag_path(tag) %></i>
                  </div>
                <% end %>
                <% if item.post_id? %>
                  <% item.post.tag_list.map.each do |tag| %>
                    <div class="tags">
                      <i><%= link_to tag, tag_path(tag) %></i>
                    </div>
                  <% end %>
                <% end %>
              </div>
          </div>
              	
                  <div class="btn-group pull-right">
                    <%= link_to like_post_path(item), method: :put, class: "btn btn-default btn-xs" do %>
                      <span class="glyphicon glyphicon-chevron-up"></span>
                      <%= item.get_upvotes.size %>
                    <% end %>
                    <%= link_to dislike_post_path(item), method: :put, class: "btn btn-default btn-xs" do %>
                      <span class="glyphicon glyphicon-chevron-down"></span>
                      <%= item.get_downvotes.size %>
                    <% end %>
                    <% if item.post_id? %>
                    <%= link_to repost_post_path(item.post), method: :post, class: "btn btn-default btn-xs" do %>
                				<span class="glyphicon glyphicon-retweet"></span>
                				<%= item.post.share_count %>
                  		<% end %>
                    <% else %>
                      <%= link_to repost_post_path(item), method: :post, class: "btn btn-default btn-xs" do %>
                				<span class="glyphicon glyphicon-retweet"></span>
                				<%= item.share_count %>
                  		<% end %>
                		<% end %>
              			<%= link_to item, class: "btn btn-default btn-xs" do %>
              				<span class="glyphicon glyphicon-comment"></span>
              				<%= item.comments.count %>
              			<% end %>
              			<%= link_to item, class: "btn btn-default btn-xs" do %>
              				<span class="glyphicon glyphicon-flash"></span>
              				<%= 3 %>
              			<% end %>
                	</div>
                </div>
        	    </div>
        		</div>
        </div>
      </div>

          
    <% end %>
  </div>
</div>

<div class="user-right-column">
  <% if user_signed_in?  %>
    <%= render "posts/quick_form" %>
	<% end %> 
</div>

app/views/static_pages/home.js.erb
$('#post-icons').html("<%= escape_javascript(render :partial => 'posts/icons', link: @post) %>");