config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    member do
      put "like", to:    "posts#upvote"
      put "dislike", to: "posts#downvote"
      post :repost
    end
    resources :comments do
      member do
        put "like", to:    "comments#upvote"
        put "dislike", to: "comments#downvote"
      end
      resources :notations
    end
  end
  resources :users do
    member do
      get :following, :followers
    end
  end
  get 'feed', to: 'static_pages#home'
  get 'static_pages/help'
  get 'y/:tag', to: 'tags#show', as: :tag
  get 'yarnns', to: 'tags#index'
  match '/about', to: 'static_pages#about', via: 'get'
  put 'ipsum', to: "words#generate_ipsum"
  get 'ipsum', to: "words#generate_ipsum"
  
  resources :relationships, only: [:create, :destroy]

  resources :notifications do
    member do
      get :toggle_read
    end
  end
  
  resources :sharings,      only: [:create, :destroy]
  
  authenticated do
    root :to => 'static_pages#home', as: :authenticated
  end

  root :to => 'home#index'
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post 
  belongs_to :user
  has_many :notations, dependent: :destroy
  
  validates :content, presence: true, length: { minimum: 3 }
  acts_as_votable

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
  before_action :load_post
  before_action :authenticate_user!, except: [:show]

  def new
    @comment = @post.comments.new
    respond_to do |format|               
      format.js
    end
  end
  
  def create
    @comment = @post.comments.new(allowed_params) 
    @comment.user_id = current_user.id if current_user
    if @comment.save
      unless current_user.id == @post.user_id
      Notification.create!(post_id: @post.id, comment_id: @comment.id, 
                                recipient_id: @post.user_id, notified_by_id: current_user.id, 
                                notification_type: "comment")
      end
      redirect_to @post, notice: "Comment created."
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    respond_to do |format|
      if @comment.update(allowed_params)
        format.html { redirect_to @post, notice: 'Comment was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @post, notice: 'Comment was deleted.' }
    end
  end
  
  def upvote
    if @comment.user_id != current_user.id
      @comment.upvote_by current_user
      
      voltaire_plus(1, :reputation, @comment.user_id)
      respond_to do |format|
        format.html { redirect_to @post }
        format.js
      end
    end
  end
  
  def downvote
    if @comment.user_id != current_user.id
      @comment.downvote_by current_user
      
      voltaire_minus(1, :reputation, @comment.user_id)
      respond_to do |format|
        format.html { redirect_to @post }
        format.js
      end
    end
  end

  private
  
  def allowed_params
    params.require(:comment).permit(:content, :user_id, :post_id)
  end
  
  def set_comment
    @comment = Comment.find(params[:id])
  end
  
  def load_post
    @post = Post.find(params[:post_id])
  end
end

app/views/comments/_comments.html.erb
<% @comments.each do |comment| %>
  <div class="link row clearfix">
    <div class="comment-box">
  		
  		<div class="row">
  	    <div class="col-md-2">
  	    	<%= link_to user_path(comment.user) do
  		     	image_tag(comment.user.avatar.url, width: 40, class: "img-circle pull-left")
  		  	end %>
  			</div>
        <div class="col-md-10-offset-2">
          <div class="comment-text"><%= comment.content %></div>
        </div>
  		</div>
      
      <div class="row">
        <div class="col-md-2">
          &nbsp;
        </div>
        <div class="col-md-10-offset-2">
  		  	<h5 style="margin-top: 0px">
  		  	  <small class="author"><%= link_to comment.user.username, user_path(comment.user) %> <span class="glyphicon glyphicon-star"></span> <%= comment.user.reputation %> 
  		  	    - <%= time_ago_in_words(comment.created_at) %> ago</small>
  		  	</h5>
  		  </div>
      </div>
    
      <div class="row">
        <div class="col-md-2">
          &nbsp;
        </div>
        
        <div class="col-md-10-offset-2">
        	<div class="btn-group">
        			<%= link_to @post, class: "btn btn-primary btn-xs" do %>
        				<span class="glyphicon glyphicon-flash" style="color: #ededed;"></span>
        				<%= 3 %>
        			<% end %>
        			<%= link_to like_post_comment_path(@post, comment), method: :put, class: "btn btn-default btn-xs" do %>
                <span class="glyphicon glyphicon-chevron-up"></span>
                <%= comment.get_upvotes.size %>
              <% end %>
              <%= link_to dislike_post_comment_path(@post, comment), method: :put, class: "btn btn-default btn-xs" do %>
                <span class="glyphicon glyphicon-chevron-down"></span>
                <%= comment.get_downvotes.size %>
              <% end %>
        	</div>
          <% if comment.user == current_user %>
          	<div class="btn-group pull-right" style="margin-right: 4%">
            	<%= link_to edit_post_comment_path(@post, comment), class: "btn btn-default btn-xs", style: "color: #039087;" do %>
            		<span class="glyphicon glyphicon-cog"></span>
            	<% end %>
            	<%= link_to post_comment_path(@post, comment), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default btn-xs", style: "color: #039087;" do %>
            		<span class="glyphicon glyphicon-trash"></span>
            	<% end %>
          	</div>
          <% end %>
        </div>
      </div>
      
      <div class="row">
        
        <div class="col-md-10 col-md-offset-2">
          <br>
            <% if comment.notations.any? %>
              <%= render 'notations/notations', comment: comment %>
            <% end %>
            <div class="notation-reply">
              <%= link_to "reply", new_post_comment_notation_path(@post, comment) %>
            </div>
  		  </div>
      </div>
    
    </div>
  </div>
<% end %>

app/views/comments/_form.html.erb
<div class="log-form">
<%= form_for [@post, @comment] do |f| %>
  <% if @comment.errors.any? %>
      <div class="error_messages">
        <h3>Please correct the following errors.</h3>
        <ul>
        <% @comment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    
      <% if current_user.reputation < 150 %>
        <%= f.text_area :content, placeholder: "what do you think about this? limit 200 characters", rows: 3, maxlength: 200 %>
      <% else %>
        <%= f.text_area :content, placeholder: "what do you think about this? limit 300 characters", rows: 3, maxlength: 300 %>
      <% end %>
      
      <br />
    
    <br />
    <%= f.submit "Comment" %>

<% end %>
</div>

app/views/comments/edit.html.erb
<%= render 'form', comment: @comment %>

app/views/comments/new.html.erb
<div id="content-wrap">
<div class="title-box">New Comment</div>

<%= render 'form' %>

</div>