config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    member do
      put "like", to:    "posts#upvote"
      put "dislike", to: "posts#downvote"
      post :repost
    end
    resources :comments do
      member do
        put "like", to:    "comments#upvote"
        put "dislike", to: "comments#downvote"
      end
      resources :notations
    end
  end
  resources :users do
    member do
      get :following, :followers
    end
  end
  get 'feed', to: 'static_pages#home'
  get 'static_pages/help'
  get 'y/:tag', to: 'tags#show', as: :tag
  get 'yarnns', to: 'tags#index'
  match '/about', to: 'static_pages#about', via: 'get'
  put 'ipsum', to: "words#generate_ipsum"
  get 'ipsum', to: "words#generate_ipsum"
  
  resources :relationships, only: [:create, :destroy]

  resources :notifications do
    member do
      get :toggle_read
    end
  end
  
  resources :sharings,      only: [:create, :destroy]
  
  authenticated do
    root :to => 'static_pages#home', as: :authenticated
  end

  root :to => 'home#index'
end

app/models/notification.rb
class Notification < ApplicationRecord
  enum notification_type: { comment: 0, notation: 1, message: 2, follow: 3, unfollow: 4, dispute: 5, repost: 6 }
  enum read: { read: true, unread: false }
  belongs_to :notified_by, class_name: 'User'
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def index
    @notifications = Notification.where({ read: false, recipient_id: current_user.id }).order('created_at DESC')
  end
  
  def toggle_read
    @notification = Notification.find(params[:id])
    if @notification.unread?
      @notification.read! 
    elsif @notification.read?
      @notification.unread!
    end
    redirect_to notifications_path
  end
end

app/views/notifications/index.html.erb
<div id="content-wrap" style="width: 1080px;">
  <div class="left-column" style="width: 80%;">
    <div class="log-form">
      <div class="title-box">Notifications</div>
    </div>
    
  <% if @notifications.count > 21 %>
    <div class ="pagination-container">
      <%= paginate @notifications %>
    </div>
  <% end %>    
  
    <div class ="log-form">
      <% if @notifications.any? %>
        <% @notifications.each do |notification| %>
            <div class="table">
              <div class="table-row">
                <div class="table-cell" style="width: 10%;">
                  <%= image_tag User.find(notification.notified_by).avatar.url, width: 40, class: "img-circle" %>  
                </div>
                
                <% if notification.notification_type == "comment" %>
                  <div class="table-cell" style="width: 78%;">
                    <i class="glyphicon glyphicon-comment"></i>&nbsp;
                    <%= link_to User.find(notification.notified_by).username, user_path(notification.notified_by) %> 
                    commented on your post <%= link_to Post.find(notification.post_id).title, post_path(notification.post_id) %>
                    <br />
                    <div class="small">
                      <%= time_ago_in_words(notification.created_at) %> ago
                    </div>                  
                  </div>
                <% end %>
                
                <% if notification.notification_type == "repost" %>
                  <div class="table-cell" style="width: 78%;">
                    <i class="glyphicon glyphicon-retweet"></i>&nbsp;
                    <%= link_to User.find(notification.notified_by).username, user_path(notification.notified_by) %> 
                    reposted <%= link_to Post.find(notification.post_id).title, post_path(notification.post_id) %> 
                    <br />
                    <div class="small">
                      <%= time_ago_in_words(notification.created_at) %> ago
                    </div>                  
                  </div>
                <% end %>
                
                <% if notification.notification_type == "notation" %>
                  <div class="table-cell" style="width: 78%;">
                    <i class="glyphicon glyphicon-comment"></i>&nbsp;
                    <%= link_to User.find(notification.notified_by).username, user_path(notification.notified_by) %> 
                    replied to your comment on the post <%= link_to Post.find(notification.post_id).title, post_path(notification.post_id) %>
                    <br />
                    <div class="small">
                      <%= time_ago_in_words(notification.created_at) %> ago
                    </div>                  
                  </div>
                <% end %>
                
                <% if notification.notification_type == "message" %>
                  <div class="table-cell" style="width: 78%;">
                    <i class="glyphicon glyphicon-envelope"></i>&nbsp;
                    <%= link_to User.find(notification.notified_by).username, user_path(notification.notified_by) %> 
                    sent you a private 
                    <%= link_to 'message', conversation_path(notification.conversation_id) %> 
                    <br />
                    <div class="small">
                      <%= time_ago_in_words(notification.created_at) %> ago
                    </div>
                  </div>
                <% end %>
                
                <% if notification.notification_type == "follow" %>
                  <div class="table-cell" style="width: 78%;">
                    <i class="glyphicon glyphicon-heart"></i>&nbsp;
                    <%= link_to User.find(notification.notified_by).username, user_path(notification.notified_by) %> 
                    started following you 
                    <br />
                    <div class="small">
                      <%= time_ago_in_words(notification.created_at) %> ago
                    </div>
                  </div>
                <% end %>
                
                <% if notification.notification_type == "unfollow" %>
                  <div class="table-cell" style="width: 78%;">
                    <i class="glyphicon glyphicon-heart-empty"></i>&nbsp;
                    <%= link_to User.find(notification.notified_by).username, user_path(notification.notified_by) %> 
                    quit following you 
                    <br />
                    <div class="small">
                      <%= time_ago_in_words(notification.created_at) %> ago
                    </div>
                  </div>
                <% end %>
                
                <div class="table-cell" style="width: 12%;">
                  <div class="small">
                    <%= link_to 'mark as read', toggle_read_notification_path(notification) %>
                  </div>
                </div>
                
              </div>
            </div>
        <% end %>
      <% else %>
      You have no notifications.
      <% end %>
    </div>
  </div>
</div>