config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    member do
      put "like", to:    "posts#upvote"
      put "dislike", to: "posts#downvote"
      post :repost
    end
    resources :comments do
      member do
        put "like", to:    "comments#upvote"
        put "dislike", to: "comments#downvote"
      end
      resources :notations
    end
  end
  resources :users do
    member do
      get :following, :followers
    end
  end
  get 'feed', to: 'static_pages#home'
  get 'static_pages/help'
  get 'y/:tag', to: 'tags#show', as: :tag
  get 'yarnns', to: 'tags#index'
  match '/about', to: 'static_pages#about', via: 'get'
  put 'ipsum', to: "words#generate_ipsum"
  get 'ipsum', to: "words#generate_ipsum"
  
  resources :relationships, only: [:create, :destroy]

  resources :notifications do
    member do
      get :toggle_read
    end
  end
  
  resources :sharings,      only: [:create, :destroy]
  
  authenticated do
    root :to => 'static_pages#home', as: :authenticated
  end

  root :to => 'home#index'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  belongs_to :post, optional: :true
  
  strip_attributes
  enum type: { standard: 0, serious: 1, personal: 2, opinion: 3 }

  validates :content, presence: true, length: { minimum: 3 }
  
  mount_uploader :image, ImageUploader
  mount_uploader :video, VideoUploader
  mount_uploader :audio, AudioUploader
  require 'streamio-ffmpeg'
  
  def post_type
    if post_id?
      "repost"
    else
      "post"
    end
  end

  acts_as_taggable
  ActsAsTaggableOn.force_lowercase = true
  ActsAsTaggableOn.force_parameterize = true
  acts_as_votable

  def maximum_amount_of_tags
    number_of_tags = tag_list_cache_on("tags").uniq.length
    errors.add(:base, "Only 1 category allowed") if number_of_tags > 3
  end
  
  private
    def image_size_validation
      errors[:image] << "should be less than 500KB" if image.size > 0.5.megabytes
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :upvote, :downvote, :repost]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    if user_signed_in?
      @post = current_user.posts.build
    end
    if params[:tag]
      @posts = Post.tagged_with(params[:tag])
    else
      @posts = Post.all.order('created_at DESC')
    end
    respond_to do |format| 
      format.html
      format.js
    end
  end

  def show
    @comments = @post.comments.order("created_at DESC").includes(:notations)
    @comment = Comment.new
    respond_to do |format| 
      format.html
      format.js
    end
  end

  def new
    @post = current_user.posts.build
    respond_to do |format| 
      format.html
      format.js
    end
  end

  def edit
  end

  def create
    @post = current_user.posts.build(post_params)
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
        format.js
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    if @post.post_id?
      unless current_user.id == @post.post.user_id
        voltaire_minus(1, :reputation, @post.post.user_id)
      end
      @post.post.decrement!(:share_count)
    end
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully deleted.' }
      format.json { head :no_content }
    end
  end
  
  def repost
    post = current_user.posts.create(post_id: @post.id, content: "Repost")
    if post.save
      unless current_user.id == @post.user_id
        voltaire_plus(1, :reputation, @post.user_id)
      
      Notification.create!(post_id: @post.id, 
                                recipient_id: @post.user_id, notified_by_id: current_user.id, 
                                notification_type: "repost")
      end
      @post.increment!(:share_count)
      respond_to do |format|
        format.html { redirect_to feed_url, notice: 'Repost was successful.' }
      end
    else
      redirect_to :back, alert: "Unable to repost."
    end
  end
  
  def upvote
    if @post.user != current_user
      @post.upvote_by current_user
    
      voltaire_plus(1, :reputation, @post.user_id)
      respond_to do |format|
        format.html { redirect_to @post }
        format.js
      end
    end
  end
  
  def downvote
    if @post.user != current_user
      @post.downvote_by current_user
  
      voltaire_minus(1, :reputation, @post.user_id)
      respond_to do |format|
        format.html { redirect_to @post }
        format.js
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:url, :content, :user_id, :tag_list, 
                                    :image, :video, :audio, :type, :post_id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comments.html.erb
<div class="main-content">
  <%= render "comments/comments" %>

  <% if @post.comments.count != 0 %>
    <%= link_to new_post_comment_path(@post), :remote => true do %>
      <a href="#comment">New Comment</a>
    <% end %>
  <% end %>
</div>

app/views/posts/_form.html.erb
<div class="log-form">
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    
    <div class="form-group">
    <% if current_user.reputation < 250 %>
      <%= f.text_area :content, placeholder: "quick post", rows: 4, maxlength: 400 %>
      <div id="chars" class="small pull-right"><i>limit 400 characters</i></div>
    <% else %>
      <%= f.text_area :content, placeholder: "quick post", rows: 4, maxlength: 1000 %>
      <div id="chars" class="small pull-right"><i>limit 1000 characters</i></div>
    <% end %>
    </div>
    <div class="form-group">
    <%= f.text_field :url, placeholder: "link URL" %>
    </div>
    
    <div class="form-group">
    <div class="small"><i> Add up to three category names. *Separate categories with commas. Example: 
    "movies, horror movies, Nightmare on Elm Street"</i></div>
    <%= f.text_field :tag_list, value: @post.tag_list.join(", ")   %>
    </div>

    <div class="form-group">
    <%= f.label :image %> 
    <%=  f.file_field :image %>

    <%= f.label :video %> 
    <%=  f.file_field :video %>

    <%= f.label :audio %> 
    <%=  f.file_field :audio %>
    </div>
  <br>
 
    <%= f.submit "Submit" %>


<% end %>
</div>

app/views/posts/_icons.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
    <%= f.label :title %><br>
    <%= f.text_field :title, :autofocus => true %>
  <br>
   
    <%= f.label :url %><br>
    <%= f.text_field :url, :autofocus => true %>
  <br>

    <%= f.label :tag_list %><i> Add up to three category names. *Separate categories with commas. Example: 
    "movies, horror movies, Nightmare on Elm Street"</i>
    <%= f.text_field :tag_list, :autofocus => true, value: @post.tag_list.join(", ")   %>

  <br>

    <%= f.label :image %> 
    <%=  f.file_field :image, :autofocus => true %>
  <br>
    <%= f.label :video %> 
    <%=  f.file_field :video, :autofocus => true %>
  <br>
    <%= f.label :audio %> 
    <%=  f.file_field :audio, :autofocus => true %>
  <br>

<% end %>

app/views/posts/_left.html.erb
<div class="main-avatar">
  <%= image_tag(@post.user.avatar.url, width: 145, class: "img-circle" ) %>
    <br />
  <h4><%= @post.user.username %></h4> 
  
  <% if @post.user.name? %>
    <%= @post.user.name %> <span class="glyphicon glyphicon-star"></span> <%= @post.user.reputation %>
  <% else %>
    <%= "Mysterious Stranger" %> <span class="glyphicon glyphicon-star"></span> <%= @post.user.reputation %>
  <% end %>
</div>

app/views/posts/_quick_form.html.erb
<% content_for :javascript do %>
  <script type="text/javascript">
    $(document).ready(function() {
   
      var maxLength = 400;
      $('textarea').keyup(function() {
        var length = $(this).val().length;
        var length = maxLength-length;
        $('#chars').text(length);
      });
   
    });
  </script>
<% end %>

<div class="log-form">
  <%= form_for(@post) do |f| %>
    <% if @post.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
  
        <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
      <% if current_user.reputation < 250 %>
        <%= f.text_area :content, placeholder: "quick post, limit 400 characters", rows: 3, maxlength: 400 %>
      <% else %>
        <%= f.text_area :content, placeholder: "quick post, limit 1000 characters", rows: 3, maxlength: 1000 %>
      <% end %>
      
      <br />
      
    <% if false %>
      <%= link_to "#", id: "post-icons", :remote => true do %>
        <%= image_tag("icons/camera.png", width: 24, alt: "camera", style: "margin-right: 9px;") %>
        <%= image_tag("icons/microphone.png", width: 24, alt: "microphone", style: "margin-right: 9px;") %>
        <%= image_tag("icons/film.png", width: 24, alt: "film", style: "margin-right: 9px;") %>
        <%= image_tag("icons/categories.png", width: 24, alt: "categories", style: "margin-right: 9px;") %>
        <%= image_tag("icons/link.png", width: 24, alt: "link") %>
      <% end %>
    <% end %>

    <%= f.submit "Submit" %>
    
  <% end %>
</div>

app/views/posts/_showpost.html.erb
<div class="main-content">
  <div class="link row clearfix">
    <div class="post-box">
      <div class="comment-box">
  		  <div class="row">

  			
  			  <div class="col-md-11 col-md-offset-1">
  		  	
            <% if @post.user == current_user %>

            	<div class="btn-group pull-right">
                <% unless @post.post_id? %>
                	<%= link_to edit_post_path(@post), class: "btn btn-xs", style: "color: #039087;" do %>
                		<span class="glyphicon glyphicon-cog"></span>
                	<% end %>
                <% end %>
              	
              	<%= link_to @post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-xs", style: "color: #039087;" do %>
              		<span class="glyphicon glyphicon-trash"></span>
              	<% end %>
            	</div>
            <% end %>
  		  	
    		    <h5 style="margin-top: 0px"> 
    		  	<% if @post.post_id? %>
    		  	 <small class="author"><span class="glyphicon glyphicon-retweet"></span> Reposted by <%= link_to @post.user.username, user_path(@post.user) %> <span class="glyphicon glyphicon-star"></span> <%= @post.user.reputation %>
    		  	<% else %>
    		  	<small class="author"><%= link_to @post.user.username, user_path(@post.user) %> <span class="glyphicon glyphicon-star"></span> <%= @post.user.reputation %>
            <% end %> 
             - <%= time_ago_in_words(@post.created_at) %> ago in
      		  	<% @post.tag_list.map.each do |tag| %>
                <div class="tags">
                  <i><%= link_to tag, tag_path(tag) %></i>
                </div>
              <% end %>
            <% if @post.post_id? %>
              <br />Originally <%= link_to "posted", post_path(@post.post) %> by <%= link_to @post.post.user.username, user_path(@post.post.user) %> 
              <span class="glyphicon glyphicon-star"></span> <%= @post.post.user.reputation %>
              - <%= time_ago_in_words(@post.post.created_at) %> ago
            <% end %>
            </small></h5>
          
            <div class="post-text">
              <% if @post.post_id? %>
        			  <%= if @post.post.image? 
                  image_tag @post.post.image, class: "image"
                end %>
                <%= if @post.post.video? 
                  video_tag @post.post.video, class: "image", :controls => true
                end %>
                <%= if @post.post.audio? 
                  audio_tag @post.post.audio, class: "audio", :controls => true
                end %>
                <br />
                <%= @post.post.content %>
              <% else %>
        			  <%= if @post.image? 
                  image_tag @post.image, class: "image"
                end %>
                <%= if @post.video? 
                  video_tag @post.video, class: "image", :controls => true
                end %>
                <%= if @post.audio? 
                  audio_tag @post.audio, class: "audio", :controls => true
                end %>
                <br />
                <%= @post.content %>
              <% end %>
             
              <% if @post.user.signature? %>
                <div class="signature"><%= @post.user.signature %></div>
              <% end %>
            </div>
          
            <div class="post-buttons">
              <div class="btn-group">
            		<% if @post.url? %>
            			<%= link_to @post.url, class: "btn btn-primary btn-xs" do %>
            				<span class="glyphicon glyphicon-link" style="color: #ededed;"></span>
            			<% end %>
            		<% else %>
            			<%= link_to "#", class: "btn btn-default btn-xs", style: "color: #ccc;" do %>
            				<span class="glyphicon glyphicon-link"></span>
            			<% end %>
            		<% end %>
            		<% if @post.url? %>
            			<%= link_to @post.url, class: "btn btn-primary btn-xs" do %>
            				<span class="glyphicon glyphicon-globe" style="color: #ededed;"></span>
            				<%= 1821 %>
            			<% end %>
            		<% else %>
            			<%= link_to "#", class: "btn btn-default btn-xs", style: "color: #ccc;" do %>
            				<span class="glyphicon glyphicon-globe"></span>
            			<% end %>
            		<% end %>
          		</div>
          		
          		<div class="btn-group">
          			<%= link_to "#", class: "btn btn-primary btn-xs" do %>
          				<span class="glyphicon glyphicon-comment" style="color: #ededed;"></span>
          				<span style="color: #ededed;"><%= @post.comments.count %></span>
          			<% end %>
          			<%= link_to @post, class: "btn btn-primary btn-xs" do %>
          				<span class="glyphicon glyphicon-flash" style="color: #ededed;"></span>
          				<%= 3 %>
          			<% end %>
          	  </div>
          	
              <div class="btn-group pull-right">
                <%= link_to like_post_path(@post), method: :put, class: "btn btn-default btn-xs" do %>
                  <span class="glyphicon glyphicon-chevron-up"></span>
                  <%= @post.get_upvotes.size %>
                <% end %>
                <%= link_to dislike_post_path(@post), method: :put, class: "btn btn-default btn-xs" do %>
                  <span class="glyphicon glyphicon-chevron-down"></span>
                  <%= @post.get_downvotes.size %>
                <% end %>
                <% if @post.post_id? %>
                <%= link_to repost_post_path(@post.post), method: :post, class: "btn btn-default btn-xs" do %>
            				<span class="glyphicon glyphicon-retweet"></span>
            				<%= @post.post.share_count %>
              		<% end %>
                <% else %>
                  <%= link_to repost_post_path(@post), method: :post, class: "btn btn-default btn-xs" do %>
            				<span class="glyphicon glyphicon-retweet"></span>
            				<%= @post.share_count %>
              		<% end %>
            		<% end %>          
            	</div>
            	
            </div>
    	    </div>
    		</div>
      </div>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<div id="content" class="col-md-6 col-md-offset-3">

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

</div>

app/views/posts/index.html.erb
<div class="user-left-column">
  <%= render 'posts/left' %>
</div>

<div class="user-mid-column">
  <div id="content" class="col-md-12">

    <% @posts.each do |post| %>
      <div class="main-content">
        <div class="link row clearfix">
          <div class="post-box">
    		
    		    <div class="row">
        	    <div class="col-md-2">
        	    	<%= link_to user_path(post.user) do
        		     	image_tag(post.user.avatar.url, width: 55, class: "img-circle pull-left")
        		  	end %>
        			</div>
    			
        			<div class="col-md-10-offset-2">
        			  <% if post.user == current_user %>
                	<div class="btn-group pull-right">
                  <% unless post.post_id? %>
                  	<%= link_to edit_post_path(post), class: "btn btn-xs", style: "color: #039087;" do %>
                  		<span class="glyphicon glyphicon-cog"></span>
                  	<% end %>
                  <% end %>
                	<%= link_to post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-xs", style: "color: #039087;" do %>
                		<span class="glyphicon glyphicon-trash"></span>
                	<% end %>
                	</div>
                <% end %>
                <h5 style="margin-top: 0px"> 
        		  	<% if post.post_id? %>
        		  	 <small class="author"><span class="glyphicon glyphicon-retweet"></span> Reposted by <%= link_to post.user.username, user_path(post.user) %> <span class="glyphicon glyphicon-star"></span> <%= post.user.reputation %>
        		  	<% else %>
        		  	<small class="author"><%= link_to post.user.username, user_path(post.user) %> <span class="glyphicon glyphicon-star"></span> <%= post.user.reputation %>
                <% end %> 
                 - <%= time_ago_in_words(post.created_at) %> ago in
          		  	<% post.tag_list.map.each do |tag| %>
                    <div class="tags">
                      <i><%= link_to tag, tag_path(tag) %></i>
                    </div>
                  <% end %>
                <% if post.post_id? %>
                  <br />Originally <%= link_to "posted", post_path(post.post) %> by <%= link_to post.post.user.username, user_path(post.post.user) %> 
                  <span class="glyphicon glyphicon-star"></span> <%= post.post.user.reputation %>
                  - <%= time_ago_in_words(post.post.created_at) %> ago
                <% end %>
                </small></h5>
        
                <div class="post-text">
                  <% if post.post_id? %>
            			  <%= if post.post.image? 
                      image_tag post.post.image, class: "image"
                    end %>
                    <%= if post.post.video? 
                      video_tag post.post.video, class: "image", :controls => true
                    end %>
                    <%= if post.post.audio? 
                      audio_tag post.post.audio, class: "audio", :controls => true
                    end %>
                    <br />
                    <%= post.post.content %>
                  <% else %>
            			  <%= if post.image? 
                      image_tag post.image, class: "image"
                    end %>
                    <%= if post.video? 
                      video_tag post.video, class: "image", :controls => true
                    end %>
                    <%= if post.audio? 
                      audio_tag post.audio, class: "audio", :controls => true
                    end %>
                    <br />
                    <%= post.content %>
                  <% end %>
                </div>
                
                <div class="post-buttons">
                  <div class="btn-group">
                		<% if post.url? %>
                			<%= link_to post.url, class: "btn btn-primary btn-xs" do %>
                				<span class="glyphicon glyphicon-link" style="color: #ededed;"></span>
                			<% end %>
                		<% else %>
                			<%= link_to "#", class: "btn btn-default btn-xs", style: "color: #ccc;" do %>
                				<span class="glyphicon glyphicon-link"></span>
                			<% end %>
                		<% end %>
                		<% if post.url? %>
                			<%= link_to post.url, class: "btn btn-primary btn-xs" do %>
                				<span class="glyphicon glyphicon-globe" style="color: #ededed;"></span>
                				<%= 1821 %>
                			<% end %>
                		<% else %>
                			<%= link_to "#", class: "btn btn-default btn-xs", style: "color: #ccc;" do %>
                				<span class="glyphicon glyphicon-globe"></span>
                			<% end %>
                		<% end %>
              		</div>
              		<div class="btn-group">
              			<%= link_to post, class: "btn btn-primary btn-xs" do %>
              				<span class="glyphicon glyphicon-comment" style="color: #ededed;"></span>
              				<span style="color: #ededed;"><%= post.comments.count %></span>
              			<% end %>
              			<%= link_to post, class: "btn btn-primary btn-xs" do %>
              				<span class="glyphicon glyphicon-flash" style="color: #ededed;"></span>
              				<%= 3 %>
              			<% end %>
              	  </div>
              	
                  <div class="btn-group pull-right">
                    <%= link_to like_post_path(post), method: :put, class: "btn btn-default btn-xs" do %>
                      <span class="glyphicon glyphicon-chevron-up"></span>
                      <%= post.get_upvotes.size %>
                    <% end %>
                    <%= link_to dislike_post_path(post), method: :put, class: "btn btn-default btn-xs" do %>
                      <span class="glyphicon glyphicon-chevron-down"></span>
                      <%= post.get_downvotes.size %>
                    <% end %>
                    <% if post.post_id? %>
                    <%= link_to repost_post_path(post.post), method: :post, class: "btn btn-default btn-xs" do %>
                				<span class="glyphicon glyphicon-retweet"></span>
                				<%= post.post.share_count %>
                  		<% end %>
                    <% else %>
                      <%= link_to repost_post_path(post), method: :post, class: "btn btn-default btn-xs" do %>
                				<span class="glyphicon glyphicon-retweet"></span>
                				<%= post.share_count %>
                  		<% end %>
                		<% end %>        
                	</div>
                </div>
            	 </div>
        		</div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="user-right-column">
  <% if user_signed_in?  %>
    <div class="quick-post-box">
      <div class="col-md-12">
        <%= render "posts/quick_form" %>
      </div>
    </div>
	<% end %> 
</div>

app/views/posts/index.js.erb
$('#post-icons').html("<%= escape_javascript(render :partial => 'posts/icons') %>");

app/views/posts/new.html.erb
<div id="content" class="col-md-6 col-md-offset-3">

<%= render 'form', link: @post %>

<%= link_to 'Back', posts_path %>

</div>

app/views/posts/new.js.erb
$('#post-icons').html("<%= escape_javascript(render :partial => 'posts/icons') %>");

app/views/posts/show.html.erb
<div class="user-left-column">
  <%= render 'posts/left' %>
</div>

<div class="user-mid-column">
  <div id="content" class="col-md-12">
    <%= render 'showpost' %>
    <%= render 'comments' %>
  </div>
</div>

<div class="user-right-column">
  <% if user_signed_in? %>
    <%= render "comments/form" %><br/>
  <% else %>
    <div class="small" style="color: #fc0000;"><em><strong>You must be logged in to comment.</strong></em></div>
  <% end %>
</div>

app/views/posts/show.js.erb
$('#comment-open').html("<%= escape_javascript(render :partial => 'comments/form') %>");